### ISSUE TITLE
Nav Bar Styling - Post page

### ISSUE THREAD

**Issue by thianhlu** [wordpress-mobile/WordPress-Editor-iOS#151]
![photo](https://cloud.githubusercontent.com/assets/204184/4079806/276f82bc-2ed9-11e4-8ccd-17df08e9189c.PNG)
- [x] Color of nav is wrong. We need to match the regular WP app. Hex #2ea2cc
- [x] Cancel/Close being replaced by icons. See #130
- [x] In new posts, Change Publish to Post
- [x] Post/Update button has wrong weight. It should be 600
- [x] Inactive color is incorrect. Hex #40a5ce
- [x] Remove 1px gray bar under Nav bar.
- [x] Positioning of the Preview / Options btns need to be moved down 2px (retina)
- [x] Margin on the Preview / Options btns https://cloudup.com/cFPWtXlqiM4

_Everything at @2x_
