### ISSUE TITLE
Match editor markup to wp-admin: master issue

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-Editor-iOS#501]
an aggregated list of issues to keep us on track for matching our HTML markup to wp-admin

- [x] whitespace cleanup - suppress all `&nbsp;` https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/500
- [x] add better html hierarchy for readability https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/502
- [x] standardize `p` element around paragraphs in posts drafted on web https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/503
- [ ] shortcodes getting linked/stripped upon publish https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/586
- [ ] if first line is bold, doesn't get wrapped in `<p>`s https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/411
- [x] multi-line blockquote interactions https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/499
- [x] standardize bold & italic styling btw html & visual editor: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/544

**Comment by meremagee** [comment]
moving to 4.9

**Comment by meremagee** [comment]
note - wp-admin doesn't suppress _all_ nbsp's. we now render the html the same as wp-admin text, which will include occasional, random-seeming nbsp's. It's much cleaner overall.

**Comment by bummytime** [comment]
Closing this master issue because #411 and #586 can stand on their own.
