### ISSUE TITLE
Formatbar updates (master list)

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-Editor-iOS#675]
- [x] Disabled toolbar and buttons (updated design) #657 
- [x] Default toolbar and buttons (updated design) #658 
- [x] Active button state (updated design) #659 
- [x] Animate format bar selection (updated design) #660 
- [x] Formatbar spacing on mobile (updated design) #661 
- [x] Formatbar spacing on tablet (updated design) #662 
- [x] Onboarding for horizontal scroll users #676

**Comment by thianhlu** [comment]
- [ ] @thianhlu Add Chevron image

**Comment by thianhlu** [comment]
@bummytime here is svg and PDF (includes vector).
https://cloudup.com/cZhdbyqhYW0

Let me know if you want me to export with shadow or apply programmatically. Also, do you want me to export in black/white and use tint to apply correct color.

**Comment by thianhlu** [comment]
CSS for shadow is:
box-shadow: -1px 0px 2px 0px rgba(46,68,83,0.50);

**Comment by bummytime** [comment]
All done!
